"""Semantic divergence detection using sentence embeddings.

Core of the Speculative Turn-taking algorithm:
Compare pre-computed prediction embeddings against actual user speech
to detect meaningful interruptions vs backchannels.
"""
import numpy as np
from sentence_transformers import SentenceTransformer
from scipy.spatial.distance import cosine
from dataclasses import dataclass
from enum import Enum
from typing import Optional


class DivergenceAction(Enum):
    """Action to take based on divergence score."""
    IGNORE = "ignore"        # Backchannel - let AI continue speaking
    MONITOR = "monitor"      # Accumulate more tokens before deciding
    INTERRUPT = "interrupt"  # Real interruption - stop AI


@dataclass
class DivergenceResult:
    """Result of a divergence evaluation."""
    score: float              # Cosine distance (0=identical, 1=orthogonal, 2=opposite)
    action: DivergenceAction
    closest_prediction: Optional[str] = None


class DivergenceDetector:
    """
    Detects semantic divergence between predicted and actual user speech.

    Uses a lightweight sentence embedding model (all-MiniLM-L6-v2, ~80MB)
    to compute cosine distance between:
    - Pre-computed prediction embeddings (what we think the user will say)
    - Actual partial user speech embeddings (what the user is saying)

    Performance: ~10ms per embedding on CPU.
    """

    def __init__(
        self,
        model_name: str = "all-MiniLM-L6-v2",
        threshold_ignore: float = 0.3,
        threshold_interrupt: float = 0.6,
    ):
        print(f"[DivergenceDetector] Loading model '{model_name}'...")
        self._model = SentenceTransformer(model_name)
        self._threshold_ignore = threshold_ignore
        self._threshold_interrupt = threshold_interrupt
        self._prediction_embeddings: list[np.ndarray] = []
        self._prediction_texts: list[str] = []
        print(f"[DivergenceDetector] Model loaded successfully")

    def set_predictions(self, predictions: list[str]) -> None:
        """Pre-compute embeddings for predicted user responses.

        Called when AI starts speaking. Predictions are generated by
        Gemini Flash text API in the speculative engine.
        """
        if not predictions:
            self._prediction_embeddings = []
            self._prediction_texts = []
            return

        self._prediction_texts = predictions
        self._prediction_embeddings = [
            self._model.encode(p) for p in predictions
        ]

    def evaluate(self, actual_text: str) -> DivergenceResult:
        """Evaluate semantic divergence of actual speech against predictions.

        This is the hot path - called as each ASR token arrives (~10ms).

        Args:
            actual_text: Partial user speech transcribed so far.

        Returns:
            DivergenceResult with score and recommended action.
        """
        if not actual_text or not self._prediction_embeddings:
            return DivergenceResult(
                score=0.0,
                action=DivergenceAction.MONITOR,
            )

        # Encode actual speech (~10ms on CPU)
        actual_embedding = self._model.encode(actual_text)

        # Find minimum cosine distance across all predictions
        min_distance = float("inf")
        closest_prediction = None

        for i, pred_emb in enumerate(self._prediction_embeddings):
            distance = cosine(actual_embedding, pred_emb)
            if distance < min_distance:
                min_distance = distance
                closest_prediction = self._prediction_texts[i]

        # Determine action based on thresholds
        if min_distance < self._threshold_ignore:
            action = DivergenceAction.IGNORE
        elif min_distance < self._threshold_interrupt:
            action = DivergenceAction.MONITOR
        else:
            action = DivergenceAction.INTERRUPT

        return DivergenceResult(
            score=min_distance,
            action=action,
            closest_prediction=closest_prediction,
        )

    def clear_predictions(self) -> None:
        """Clear cached prediction embeddings."""
        self._prediction_embeddings = []
        self._prediction_texts = []
