"""Semantic divergence detection using sentence embeddings.

Core of the Speculative Turn-taking algorithm:
Compare pre-computed prediction embeddings against actual user speech
to detect meaningful interruptions vs backchannels.
"""
import numpy as np
import os
from google import genai
from google.genai import types
from scipy.spatial.distance import cosine
from dataclasses import dataclass
from enum import Enum
from typing import Optional


class DivergenceAction(Enum):
    """Action to take based on divergence score."""
    IGNORE = "ignore"        # Backchannel - let AI continue speaking
    MONITOR = "monitor"      # Accumulate more tokens before deciding
    INTERRUPT = "interrupt"  # Real interruption - stop AI


@dataclass
class DivergenceResult:
    """Result of a divergence evaluation."""
    score: float              # Cosine distance (0=identical, 1=orthogonal, 2=opposite)
    action: DivergenceAction
    closest_prediction: Optional[str] = None


class DivergenceDetector:
    """
    Detects semantic divergence between predicted and actual user speech.

    Uses Gemini gemini-embedding-2-preview to compute cosine distance between:
    - Pre-computed prediction embeddings (what we think the user will say)
    - Actual partial user speech embeddings (what the user is saying)
    """

    def __init__(
        self,
        model_name: str = "gemini-embedding-2-preview",
        threshold_ignore: float = 0.3,
        threshold_interrupt: float = 0.6,
    ):
        print(f"[DivergenceDetector] Using Gemini embedding model '{model_name}'...")
        self._model_name = model_name
        self._threshold_ignore = threshold_ignore
        self._threshold_interrupt = threshold_interrupt
        self._prediction_embeddings: list[np.ndarray] = []
        self._prediction_texts: list[str] = []
        
        # Initialize Gemini Client
        self._client = genai.Client(api_key=os.environ.get("GOOGLE_API_KEY"))

    def set_predictions(self, predictions: list[str]) -> None:
        """Pre-compute embeddings for predicted user responses.

        Called when AI starts speaking. Predictions are generated by
        Gemini Flash text API in the speculative engine.
        """
        if not predictions:
            self._prediction_embeddings = []
            self._prediction_texts = []
            return

        self._prediction_texts = predictions
        
        # Fetch embeddings in batch
        try:
            response = self._client.models.embed_content(
                model=self._model_name,
                contents=predictions
            )
            self._prediction_embeddings = [np.array(emb.values) for emb in response.embeddings]
        except Exception as e:
            print(f"[DivergenceDetector] Error getting embeddings: {e}")
            self._prediction_embeddings = []

    def evaluate(self, actual_text: str) -> DivergenceResult:
        """Evaluate semantic divergence of actual speech against predictions.

        Args:
            actual_text: Partial user speech transcribed so far.

        Returns:
            DivergenceResult with score and recommended action.
        """
        if not actual_text or not self._prediction_embeddings:
            return DivergenceResult(
                score=0.0,
                action=DivergenceAction.MONITOR,
            )

        # Encode actual speech
        try:
            response = self._client.models.embed_content(
                model=self._model_name,
                contents=actual_text
            )
            actual_embedding = np.array(response.embeddings[0].values)
        except Exception as e:
            print(f"[DivergenceDetector] Error embedding actual text: {e}")
            return DivergenceResult(score=0.0, action=DivergenceAction.MONITOR)

        # Find minimum cosine distance across all predictions
        min_distance = float("inf")
        closest_prediction = None

        for i, pred_emb in enumerate(self._prediction_embeddings):
            distance = cosine(actual_embedding, pred_emb)
            if distance < min_distance:
                min_distance = distance
                closest_prediction = self._prediction_texts[i]

        # Determine action based on thresholds
        if min_distance < self._threshold_ignore:
            action = DivergenceAction.IGNORE
        elif min_distance < self._threshold_interrupt:
            action = DivergenceAction.MONITOR
        else:
            action = DivergenceAction.INTERRUPT

        return DivergenceResult(
            score=min_distance,
            action=action,
            closest_prediction=closest_prediction,
        )

    def clear_predictions(self) -> None:
        """Clear cached prediction embeddings."""
        self._prediction_embeddings = []
        self._prediction_texts = []
